maps = {
	{
		name = 'Generic',
		type = 'Generic',
		minWind = 0,
		maxWind = 2505,
		tidal = 20,
		surfaceMetal = 0.1,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Acid Foursome',
		type = 'Acid',
		minWind = 1000,
		maxWind = 2000,
		tidal = 20,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Brain Coral',
		type = 'Water',
		minWind = 300,
		maxWind = 3000,
		tidal = 29,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Cluster Freak',
		type = 'Slate',
		minWind = 5000,
		maxWind = 5000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Coast To Coast',
		type = 'Tropical',
		minWind = 0,
		maxWind = 3500,
		tidal = 15,
		surfaceMetal = 0.1,
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Comet Catcher',
		type = 'Lunar',
		minWind = 0,
		maxWind = 0,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
    {
		name = 'Core Prime Industrial Area',
		type = 'Lusch',
		minWind = 25,
		maxWind = 1500,
		tidal = 24,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Crater Isles',
		type = 'Green',
		minWind = 0,
		maxWind = 4000,
		tidal = 20,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
    {
		name = 'Crystal Maze',
		type = 'Crystal',
		minWind = 500,
		maxWind = 5000,
		tidal = 20,
		surfaceMetal = 0,
		patchMetal = 2.3,
		mohoMetal = 7,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Dark Side',
		type = 'Lunar',
		minWind = 0,
		maxWind = 0,
		tidal = 0,
		surfaceMetal = 0.1, 
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Evad River Confluence',
		type = 'Green',
		minWind = 0,
		maxWind = 2000,
		tidal = 0,
		surfaceMetal = 0.1, 
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Gasplant Plain',
		type = 'Acid',
		minWind = 2000,
		maxWind = 4000,
		tidal = 20,
		surfaceMetal = 0.1, 
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Gods of War OTA',
		type = 'Mars',
		minWind = 500,
		maxWind = 4500,
		tidal = 20,
		surfaceMetal = 0.1, 
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Gods of War SCTA',
		type = 'Mars',
		minWind = 500,
		maxWind = 4500,
		tidal = 20,
		surfaceMetal = 0.1, 
		patchMetal = 2.0,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Great Divide',
		type = 'Green',
		minWind = 0,
		maxWind = 4000,
		tidal = 0,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Great Divide 2',
		type = 'Green',
		minWind = 25,
		maxWind = 5000,
		tidal = 20,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Greenhaven',
		type = 'Green',
		minWind = 411,
		maxWind = 2500,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Hundred Isles',
		type = 'Tropical',
		minWind = 0,
		maxWind = 4000,
		tidal = 25,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'King of the Hill',
		type = 'Mars',
		minWind = 500,
		maxWind = 4500,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Lake Shore',
		type = 'Desert',
		minWind = 3800,
		maxWind = 4000,
		tidal = 3,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Lava Run',
		type = 'Lava',
		minWind = 500,
		maxWind = 3500,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Lusch Puppy',
		type = 'Lusch',
		minWind = 1000,
		maxWind = 1234,
		tidal = 18,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.5,
	},
    {
		name = "John's Pass",
		type = 'Lush',
		minWind = 3500,
		maxWind = 4000,
		tidal = 20,
		surfaceMetal = 0.1,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Lava & Two Hills',
		type = 'Lava',
		minWind = 100,
		maxWind = 3000,
		tidal = 0,
		surfaceMetal = 0.2,
		patchMetal = 2.0,
		mohoMetal = 7,
		mohoSurfaceMetal = 1.6,
	},
	{
		name = 'Lava Highground',
		type = 'Lava',
		minWind = 500,
		maxWind = 3500,
		tidal = 0,
		surfaceMetal = 0.2,
		patchMetal = 2.0,
		mohoMetal = 7,
		mohoSurfaceMetal = 1.6,
	},
	{
		name = 'Metal Heck',
		type = 'Metal',
		minWind = 0,
		maxWind = 3000,
		tidal = 0,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Painted Desert',
		type = 'Desert',
		minWind = 100,
		maxWind = 4000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Painted Desert II',
		type = 'Desert',
		minWind = 100,
		maxWind = 4000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Red Planet',
		type = 'Mars',
		minWind = 400,
		maxWind = 3200,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Sail Away',
		type = 'Tropical',
		minWind = 2500,
		maxWind = 5500,
		tidal = 24,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Sherwood',
		type = 'Green',
		minWind = 500,
		maxWind = 3500,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Show Down',
		type = 'Lush',
		minWind = 2500,
		maxWind = 4000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'The Desert Triad',
		type = 'Desert',
		minWind = 0,
		maxWind = 800,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Trout Farm',
		type = 'Urban',
		minWind = 3500,
		maxWind = 5000,
		tidal = 7,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Block Wars',
		type = 'Metal',
		minWind = 25,
		maxWind = 1500,
		tidal = 0,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Ashap Plateau',
		type = 'Mars',
		minWind = 0,
		maxWind = 4000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Anteer Strait',
		type = 'Ice',
		minWind = 200,
		maxWind = 4000,
		tidal = 25,
		surfaceMetal = 0,
		patchMetal = 2,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Seven Islands',
		type = 'Metal',
		minWind = 0,
		maxWind = 4000,
		tidal = 20,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'The Pass',
		type = 'Green',
		minWind = 100,
		maxWind = 3000,
		tidal = 0,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Metal Isles',
		type = 'Metal',
		minWind = 127,
		maxWind = 953,
		tidal = 32,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Over Crude Water',
		type = 'Metal',
		minWind = 100,
		maxWind = 4000,
		tidal = 25,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Yerrot Mountains',
		type = 'Mars',
		minWind = 0,
		maxWind = 2000,
		tidal = 0,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Metal Gridlock',
		type = 'Metal',
		minWind = 500,
		maxWind = 4500,
		tidal = 25,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Coremageddon',
		type = 'Metal',
		minWind = 1000,
		maxWind = 1500,
		tidal = 0,
		surfaceMetal = 2.3,
		patchMetal = 2.3,
		mohoMetal = 19.2,
		mohoSurfaceMetal = 19.2,
	},
	{
		name = 'Etorrep Glacier',
		type = 'Ice',
		minWind = 500,
		maxWind = 5000,
		tidal = 15,
		surfaceMetal = 0,
		patchMetal = 2.0,
		mohoMetal = 6.2,
		mohoSurfaceMetal = 0.3,
	},
	{
		name = 'Red Triangle',
		type = 'Mars',
		minWind = 1000,
		maxWind = 5500,
		tidal = 25,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'The Cold Place',
		type = 'Ice',
		minWind = 2500,
		maxWind = 5500,
		tidal = 20,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
	{
		name = 'Two Continents',
		type = 'Green',
		minWind = 0,
		maxWind = 3000,
		tidal = 22,
		surfaceMetal = 0.1,
		patchMetal = 2,
		mohoMetal = 6.3,
		mohoSurfaceMetal = 0.5,
	},
}

terrain = {
	{
		name = 'Generic',
		Geothermal = {
			modelAmount = 1,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/geothermal_marker.dds',
			},
		},
		Metal = {
			modelAmount = 3,
			models = {
				'/mods/SCTA/env/common/props/Green/rockmetal1_prop.bp',
				'/mods/SCTA/env/common/props/Green/rockmetal2_prop.bp',
				'/mods/SCTA/env/common/props/Green/rockmetal3_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/metal_marker.dds',
				'/mods/SCTA/env/common/splats/metal_marker.dds',
				'/mods/SCTA/env/common/splats/metal_marker.dds',
			},
		},
		UWMetal = {
			modelAmount = 1,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/mass_marker.dds',
			},
			size = 2
		},
	},
	{
		name = 'Desert',
		--No Geothermals
		Geothermal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Desert/metal01.dds',
				'/mods/SCTA/env/common/splats/Desert/metal02.dds',
				'/mods/SCTA/env/common/splats/Desert/metal03.dds',
			},
		},
		--No underwater Metal
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Green',
		Geothermal = {
			modelAmount = 10,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Green/vent01.dds',
				'/mods/SCTA/env/common/splats/Green/vent02.dds',
				'/mods/SCTA/env/common/splats/Green/vent03.dds',
				'/mods/SCTA/env/common/splats/Green/vent04.dds',
				'/mods/SCTA/env/common/splats/Green/vent05.dds',
				'/mods/SCTA/env/common/splats/Green/vent06.dds',
				'/mods/SCTA/env/common/splats/Green/vent07.dds',
				'/mods/SCTA/env/common/splats/Green/vent08.dds',
				'/mods/SCTA/env/common/splats/Green/vent09.dds',
				'/mods/SCTA/env/common/splats/Green/vent10.dds',
			},
		},
		Metal = {
			modelAmount = 1,
			models = {
				'/mods/SCTA/env/common/props/Green/rockmetal1_prop.bp',
				'/mods/SCTA/env/common/props/Green/rockmetal2_prop.bp',
				'/mods/SCTA/env/common/props/Green/rockmetal3_prop.bp',
				'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Green/rockmetal1.dds',
				'/mods/SCTA/env/common/splats/Green/rockmetal2.dds',
				'/mods/SCTA/env/common/splats/Green/rockmetal3.dds',
				'/mods/SCTA/env/common/splats/Green/rockmetal4.dds',
			},
		},
		UWMetal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Green/greenaquaore1.dds',
				'/mods/SCTA/env/common/splats/Green/greenaquaore2.dds',
				'/mods/SCTA/env/common/splats/Green/greenaquaore3.dds',
			},
		},
	},
	{
		name = 'Lava',
		Geothermal = {
			modelAmount = 10,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp', #TO DO?
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Lava/tvent001.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent002.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent003.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent004.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent005.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent006.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent007.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent008.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent009.dds',
				'/mods/SCTA/env/common/splats/Lava/tvent010.dds',
			},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Lava/Metal1.dds',
				'/mods/SCTA/env/common/splats/Lava/Metal2.dds',
				'/mods/SCTA/env/common/splats/Lava/Metal3.dds',
			},
		},
		--No underwater Metal
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Lunar',
		--No Geothermals
		Geothermal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Lunar/metal01.dds',
				'/mods/SCTA/env/common/splats/Lunar/metal02.dds',
				'/mods/SCTA/env/common/splats/Lunar/metal03.dds',
			},
		},
		--No underwater Metal
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Lush',
		Geothermal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
                	    	'/mods/SCTA/env/common/splats/Lush/geovent01.dds',
				'/mods/SCTA/env/common/splats/Lush/geovent02.dds',
				'/mods/SCTA/env/common/splats/Lush/geovent03.dds',
			},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Lush/lushmetal01.dds',
				'/mods/SCTA/env/common/splats/Lush/lushmetal02.dds',
				'/mods/SCTA/env/common/splats/Lush/lushmetal03.dds',
			},
		},
		UWMetal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Lush/aquaore1.dds',
				'/mods/SCTA/env/common/splats/Lush/aquaore2.dds',
				'/mods/SCTA/env/common/splats/Lush/aquaore3.dds',
			},
		},
	},	
	{
		name = 'Slate',
		Geothermal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
                	    	'/mods/SCTA/env/common/splats/Slate/slatevent01.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevent02.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevent03.dds',
			},
		},
		Metal = {
			modelAmount = 14,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Slate/slatevein01.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein02.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein03.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein04.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein05.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein07.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein08.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein09.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein11.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein12.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein13.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein14.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein15.dds',
				'/mods/SCTA/env/common/splats/Slate/slatevein16.dds',
			},
		},
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Metal',
		Geothermal = {
			modelAmount = 6,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Metal/vent01.dds',
				'/mods/SCTA/env/common/splats/Metal/vent02.dds',
				'/mods/SCTA/env/common/splats/Metal/vent03.dds',
				'/mods/SCTA/env/common/splats/Metal/vent04.dds',
				'/mods/SCTA/env/common/splats/Metal/vent05.dds',
				'/mods/SCTA/env/common/splats/Metal/vent06.dds',
			},
		},
		Metal = {
			modelAmount = 1,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/mass_marker.dds',
			},
			Size = 2,
			Hide = true,
		},
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Mars',
		Geothermal = {
			modelAmount = 1,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/geothermal_marker.dds',
			},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Mars/metal01.dds',
				'/mods/SCTA/env/common/splats/Mars/metal02.dds',
				'/mods/SCTA/env/common/splats/Mars/metal03.dds',
			},
		},
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
	{
		name = 'Ice',
		Geothermal = {
			modelAmount = 1,
			models = {
                    		'/mods/SCTA/env/common/props/generic_geothermal_prop.bp',
			},
			albedos = {
				'/mods/SCTA/env/common/splats/geothermal_marker.dds',
			},
		},
		Metal = {
			modelAmount = 3,
			models = {
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
                    		'/mods/SCTA/env/common/props/generic_metal_prop.bp', #TO DO
			},
			albedos = {
				'/mods/SCTA/env/common/splats/Ice/metal01.dds',
				'/mods/SCTA/env/common/splats/Ice/metal02.dds',
				'/mods/SCTA/env/common/splats/Ice/metal03.dds',
			},
		},
		UWMetal = {
			modelAmount = 0,
			models = {},
			albedos = {},
		},
	},
}