--[[
Contains the mapping of restriction types to restriction data in the following format:

type = {
    categories = {"cat1", "cat2", etc...},
    name = "name to display in list",
    tooltip = tooltipID,
}
--]]

restrictedUnits = {
    ARMAAP = {
        categories = {"ARMAAP"},
        name = "ARM Adv. Aircraft Plant - Produces Aircraft",
        tooltip = "Disable the ARM Adv. Aircraft Plant",
    },
    ARMAAS = {
        categories = {"ARMAAS"},
        name = "ARM Archer - Anti-Air Ship",
        tooltip = "Disable the ARM Archer",
    },
    ARMACA = {
        categories = {"ARMACA"},
        name = "ARM Adv. Construction Aircraft - Tech Level 2",
        tooltip = "Disable the ARM Adv. Construction Aircraft",
    },
    ARMACK = {
        categories = {"ARMACK"},
        name = "ARM Adv. Construction Kbot - Tech Level 2",
        tooltip = "Disable the ARM Adv. Construction Kbot",
    },
    ARMACSUB = {
        categories = {"ARMACSUB"},
        name = "ARM Adv. Construction Sub - Tech Level 2",
        tooltip = "Disable the ARM Adv. Construction Sub",
    },
    ARMACV = {
        categories = {"ARMACV"},
        name = "ARM Adv. Construction Vehicle - Tech Level 2",
        tooltip = "Disable the ARM Adv. Construction Vehicle",
    },
    ARMAH = {
        categories = {"ARMAH"},
        name = "ARM Swatter - Anti-Air Hovercraft",
        tooltip = "Disable the ARM Swatter",
    },
    ARMALAB = {
        categories = {"ARMALAB"},
        name = "ARM Adv. Kbot Lab - Produces Kbots",
        tooltip = "Disable the ARM Adv. Kbot Lab",
    },
    ARMAMB = {
        categories = {"ARMAMB"},
        name = "ARM Ambusher - Pop-up Heavy Cannon",
        tooltip = "Disable the ARM Ambusher",
    },
    ARMAMD = {
        categories = {"ARMAMD"},
        name = "ARM Protector - Anti Missile Defense System",
        tooltip = "Disable the ARM Protector",
    },
    ARMAMPH = {
        categories = {"ARMAMPH"},
        name = "ARM Pelican - Amphibious Kbot",
        tooltip = "Disable the ARM Pelican",
    },
    ARMANAC = {
        categories = {"ARMANAC"},
        name = "ARM Anaconda - Hovertank",
        tooltip = "Disable the ARM Anaconda",
    },
    ARMANNI = {
        categories = {"ARMANNI"},
        name = "ARM Annihilator - Energy weapon",
        tooltip = "Disable the ARM Annihilator",
    },
    ARMAP = {
        categories = {"ARMAP"},
        name = "ARM Aircraft Plant - Produces Aircraft",
        tooltip = "Disable the ARM Aircraft Plant",
    },
    ARMARAD = {
        categories = {"ARMARAD"},
        name = "ARM Adv. Radar Tower - Long Range Radar Tower",
        tooltip = "Disable the ARM Adv. Radar Tower",
    },
    ARMASER = {
        categories = {"ARMASER"},
        name = "ARM Eraser - Radar Jammer",
        tooltip = "Disable the ARM Eraser",
    },
    ARMASON = {
        categories = {"ARMASON"},
        name = "ARM Adv. Sonar Station - Extended Sonar",
        tooltip = "Disable the ARM Adv. Sonar Station",
    },
    ARMASP = {
        categories = {"ARMASP"},
        name = "ARM Air Repair Pad - Automatically repairs aircraft",
        tooltip = "Disable the ARM Air Repair Pad",
    },
    ARMASY = {
        categories = {"ARMASY"},
        name = "ARM Adv. Shipyard - Produces Ships",
        tooltip = "Disable the ARM Adv. Shipyard",
    },
    ARMATL = {
        categories = {"ARMATL"},
        name = "ARM Adv. Torpedo Launcher - Advanced Torpedo Launcher",
        tooltip = "Disable the ARM Adv. Torpedo Launcher",
    },
    ARMATLAS = {
        categories = {"ARMATLAS"},
        name = "ARM Atlas - Air Transport",
        tooltip = "Disable the ARM Atlas",
    },
    ARMAVP = {
        categories = {"ARMAVP"},
        name = "ARM Adv. Vehicle Plant - Produces Vehicles",
        tooltip = "Disable the ARM Adv. Vehicle Plant",
    },
    ARMAWAC = {
        categories = {"ARMAWAC"},
        name = "ARM Eagle - Radar Plane",
        tooltip = "Disable the ARM Eagle",
    },
    ARMBATS = {
        categories = {"ARMBATS"},
        name = "ARM Millennium - Battleship",
        tooltip = "Disable the ARM Millennium",
    },
    ARMBRAWL = {
        categories = {"ARMBRAWL"},
        name = "ARM Brawler - Gunship",
        tooltip = "Disable the ARM Brawler",
    },
    ARMBRTHA = {
        categories = {"ARMBRTHA"},
        name = "ARM Big Bertha - Long Range Plasma Cannon",
        tooltip = "Disable the ARM Big Bertha",
    },
    ARMBULL = {
        categories = {"ARMBULL"},
        name = "ARM Bulldog - Heavy Assault Tank",
        tooltip = "Disable the ARM Bulldog",
    },
    ARMCA = {
        categories = {"ARMCA"},
        name = "ARM Construction Aircraft - Tech Level 1",
        tooltip = "Disable the ARM Construction Aircraft",
    },
    ARMCARRY = {
        categories = {"ARMCARRY"},
        name = "ARM Colossus - Light Carrier",
        tooltip = "Disable the ARM Colossus",
    },
    ARMCH = {
        categories = {"ARMCH"},
        name = "ARM Construction Hovercraft - Tech Level 1",
        tooltip = "Disable the ARM Construction Hovercraft",
    },
    ARMCK = {
        categories = {"ARMCK"},
        name = "ARM Construction KBot - Tech Level 1",
        tooltip = "Disable the ARM Construction KBot",
    },
    ARMCKFUS = {
        categories = {"ARMCKFUS"},
        name = "ARM Cloakable Fusion Reactor - Produces Energy",
        tooltip = "Disable the ARM Cloakable Fusion Reactor",
    },
    ARMCOM = {
        categories = {"ARMCOM"},
        name = "ARM Commander - Commander",
        tooltip = "Disable the ARM Commander",
    },
    ARMCROC = {
        categories = {"ARMCROC"},
        name = "ARM Triton - Amphibious Tank",
        tooltip = "Disable the ARM Triton",
    },
    ARMCRUS = {
        categories = {"ARMCRUS"},
        name = "ARM Conqueror - Cruiser",
        tooltip = "Disable the ARM Conqueror",
    },
    ARMCS = {
        categories = {"ARMCS"},
        name = "ARM Construction Ship - Tech Level 1",
        tooltip = "Disable the ARM Construction Ship",
    },
    Armcsa = {
        categories = {"Armcsa"},
        name = "ARM Construction Seaplane - Tech Level 1",
        tooltip = "Disable the ARM Construction Seaplane",
    },
    ARMCV = {
        categories = {"ARMCV"},
        name = "ARM Construction Vehicle - Tech Level 1",
        tooltip = "Disable the ARM Construction Vehicle",
    },
    ARMDECOM = {
        categories = {"ARMDECOM"},
        name = "ARM Commander - Decoy Commander",
        tooltip = "Disable the ARM Commander",
    },
    ARMDRAG = {
        categories = {"ARMDRAG"},
        name = "ARM Dragon's Teeth - Perimeter Defense",
        tooltip = "Disable the ARM Dragon's Teeth",
    },
    ARMEMP = {
        categories = {"ARMEMP"},
        name = "ARM Stunner - EMP Missile Launcher",
        tooltip = "Disable the ARM Stunner",
    },
    ARMESTOR = {
        categories = {"ARMESTOR"},
        name = "ARM Energy Storage - Increases Energy Storage",
        tooltip = "Disable the ARM Energy Storage",
    },
    ARMFAST = {
        categories = {"ARMFAST"},
        name = "ARM Zipper - Fast Attack Kbot",
        tooltip = "Disable the ARM Zipper",
    },
    ARMFAV = {
        categories = {"ARMFAV"},
        name = "ARM Jeffy - Fast Attack Vehicle",
        tooltip = "Disable the ARM Jeffy",
    },
    ARMFDRAG = {
        categories = {"ARMFDRAG"},
        name = "ARM Floating Dragon's Teeth - Floating Dragon's Teeth",
        tooltip = "Disable the ARM Floating Dragon's Teeth",
    },
    ARMFHLT = {
        categories = {"ARMFHLT"},
        name = "ARM Stingray - Floating Heavy Laser Tower",
        tooltip = "Disable the ARM Stingray",
    },
    ARMFIDO = {
        categories = {"ARMFIDO"},
        name = "ARM Fido - Assault Kbot",
        tooltip = "Disable the ARM Fido",
    },
    ARMFIG = {
        categories = {"ARMFIG"},
        name = "ARM Freedom Fighter - Fighter",
        tooltip = "Disable the ARM Freedom Fighter",
    },
    ARMFLAK = {
        categories = {"ARMFLAK"},
        name = "ARM Flakker - Anti-Air Flak Gun",
        tooltip = "Disable the ARM Flakker",
    },
    ARMFLASH = {
        categories = {"ARMFLASH"},
        name = "ARM Flash - Fast Assault Tank",
        tooltip = "Disable the ARM Flash",
    },
    ARMFMKR = {
        categories = {"ARMFMKR"},
        name = "ARM Floating Metal Maker - Floating Metal Maker",
        tooltip = "Disable the ARM Floating Metal Maker",
    },
    ARMFORT = {
        categories = {"ARMFORT"},
        name = "ARM Fortification Wall - Perimeter Defense",
        tooltip = "Disable the ARM Fortification Wall",
    },
    ARMFRT = {
        categories = {"ARMFRT"},
        name = "ARM Defender - NS - Missile Tower - Naval Series",
        tooltip = "Disable the ARM Defender - NS",
    },
    ARMFUS = {
        categories = {"ARMFUS"},
        name = "ARM Fusion Reactor - Produces Energy",
        tooltip = "Disable the ARM Fusion Reactor",
    },
    ARMGEO = {
        categories = {"ARMGEO"},
        name = "ARM Geothermal Powerplant - Produces Energy",
        tooltip = "Disable the ARM Geothermal Powerplant",
    },
    ARMGUARD = {
        categories = {"ARMGUARD"},
        name = "ARM Guardian - Plasma Battery",
        tooltip = "Disable the ARM Guardian",
    },
    ARMHAM = {
        categories = {"ARMHAM"},
        name = "ARM Hammer - Artillery Kbot",
        tooltip = "Disable the ARM Hammer",
    },
    ARMHAWK = {
        categories = {"ARMHAWK"},
        name = "ARM Hawk - Stealth Fighter",
        tooltip = "Disable the ARM Hawk",
    },
    ARMHLT = {
        categories = {"ARMHLT"},
        name = "ARM Sentinel - Heavy Laser Tower",
        tooltip = "Disable the ARM Sentinel",
    },
    ARMHP = {
        categories = {"ARMHP"},
        name = "ARM Hovercraft Platform - Builds Hovercraft",
        tooltip = "Disable the ARM Hovercraft Platform",
    },
    ARMJAM = {
        categories = {"ARMJAM"},
        name = "ARM Jammer - Mobile Radar Jammer",
        tooltip = "Disable the ARM Jammer",
    },
    ARMJETH = {
        categories = {"ARMJETH"},
        name = "ARM Jethro - Anti-Air Kbot",
        tooltip = "Disable the ARM Jethro",
    },
    ARMLAB = {
        categories = {"ARMLAB"},
        name = "ARM Kbot Lab - Produces Kbots",
        tooltip = "Disable the ARM Kbot Lab",
    },
    ARMLANCE = {
        categories = {"ARMLANCE"},
        name = "ARM Lancet - Torpedo Bomber",
        tooltip = "Disable the ARM Lancet",
    },
    ARMLATNK = {
        categories = {"ARMLATNK"},
        name = "ARM Panther - Lightning Tank",
        tooltip = "Disable the ARM Panther",
    },
    ARMLLT = {
        categories = {"ARMLLT"},
        name = "ARM L.L.T. - Light Laser Tower",
        tooltip = "Disable the ARM L.L.T.",
    },
    ARMMAKR = {
        categories = {"ARMMAKR"},
        name = "ARM Metal Maker - Converts Energy into Metal",
        tooltip = "Disable the ARM Metal Maker",
    },
    ARMMANNI = {
        categories = {"ARMMANNI"},
        name = "ARM Penetrator - Mobile Energy Weapon",
        tooltip = "Disable the ARM Penetrator",
    },
    ARMMARK = {
        categories = {"ARMMARK"},
        name = "ARM Marky - Mobile Radar Kbot",
        tooltip = "Disable the ARM Marky",
    },
    ARMMART = {
        categories = {"ARMMART"},
        name = "ARM Luger - Mobile Artillery",
        tooltip = "Disable the ARM Luger",
    },
    ARMMAV = {
        categories = {"ARMMAV"},
        name = "ARM Maverick - Gun-slinging Kbot",
        tooltip = "Disable the ARM Maverick",
    },
    ARMMERL = {
        categories = {"ARMMERL"},
        name = "ARM Merl - Mobile Rocket Launcher",
        tooltip = "Disable the ARM Merl",
    },
    ARMMEX = {
        categories = {"ARMMEX"},
        name = "ARM Metal Extractor - Extracts Metal",
        tooltip = "Disable the ARM Metal Extractor",
    },
    ARMMH = {
        categories = {"ARMMH"},
        name = "ARM Wombat - Hovercraft Rocket Launcher",
        tooltip = "Disable the ARM Wombat",
    },
    ARMMINE1 = {
        categories = {"ARMMINE1"},
        name = "ARM Tiny Mine - Low Damage, Med. Range Mine",
        tooltip = "Disable the ARM Tiny Mine",
    },
    ARMMINE2 = {
        categories = {"ARMMINE2"},
        name = "ARM Area Mine - Low Damage, Large Range Mine",
        tooltip = "Disable the ARM Area Mine",
    },
    ARMMINE3 = {
        categories = {"ARMMINE3"},
        name = "ARM Focused Mine - Med. Damage, Small Range Mine",
        tooltip = "Disable the ARM Focused Mine",
    },
    ARMMINE4 = {
        categories = {"ARMMINE4"},
        name = "ARM HE Area Mine - Med. Damage, Large Range Mine",
        tooltip = "Disable the ARM HE Area Mine",
    },
    ARMMINE5 = {
        categories = {"ARMMINE5"},
        name = "ARM Precision Mine - High Damage, Small Range Mine",
        tooltip = "Disable the ARM Precision Mine",
    },
    ARMMINE6 = {
        categories = {"ARMMINE6"},
        name = "ARM Nuclear Mine - Nuclear Mine",
        tooltip = "Disable the ARM Nuclear Mine",
    },
    ARMMLV = {
        categories = {"ARMMLV"},
        name = "ARM Podger - Mine Layer Vehicle",
        tooltip = "Disable the ARM Podger",
    },
    ARMMMKR = {
        categories = {"ARMMMKR"},
        name = "ARM Moho Metal Maker - Converts Energy into Metal",
        tooltip = "Disable the ARM Moho Metal Maker",
    },
    ARMMOHO = {
        categories = {"ARMMOHO"},
        name = "ARM Moho Mine - Advanced Metal Extractor",
        tooltip = "Disable the ARM Moho Mine",
    },
    ARMMSHIP = {
        categories = {"ARMMSHIP"},
        name = "ARM Ranger - Missile Ship",
        tooltip = "Disable the ARM Ranger",
    },
    ARMMSTOR = {
        categories = {"ARMMSTOR"},
        name = "ARM Metal Storage - Increases Metal Storage",
        tooltip = "Disable the ARM Metal Storage",
    },
    ARMPEEP = {
        categories = {"ARMPEEP"},
        name = "ARM Peeper - Air Scout",
        tooltip = "Disable the ARM Peeper",
    },
    ARMPLAT = {
        categories = {"ARMPLAT"},
        name = "ARM Seaplane Platform - Builds Seaplanes",
        tooltip = "Disable the ARM Seaplane Platform",
    },
    ARMPNIX = {
        categories = {"ARMPNIX"},
        name = "ARM Phoenix - Bomber",
        tooltip = "Disable the ARM Phoenix",
    },
    ARMPT = {
        categories = {"ARMPT"},
        name = "ARM Skeeter - Scout Ship",
        tooltip = "Disable the ARM Skeeter",
    },
    ARMPW = {
        categories = {"ARMPW"},
        name = "ARM Peewee - Infantry Kbot",
        tooltip = "Disable the ARM Peewee",
    },
    ARMRAD = {
        categories = {"ARMRAD"},
        name = "ARM Radar Tower - Radar Tower",
        tooltip = "Disable the ARM Radar Tower",
    },
    ARMRL = {
        categories = {"ARMRL"},
        name = "ARM Defender - Missile Tower",
        tooltip = "Disable the ARM Defender",
    },
    ARMROCK = {
        categories = {"ARMROCK"},
        name = "ARM Rocko - Rocket Kbot",
        tooltip = "Disable the ARM Rocko",
    },
    ARMROY = {
        categories = {"ARMROY"},
        name = "ARM Crusader - Destroyer",
        tooltip = "Disable the ARM Crusader",
    },
    ARMSAM = {
        categories = {"ARMSAM"},
        name = "ARM Samson - Mobile Missile Launcher",
        tooltip = "Disable the ARM Samson",
    },
    ARMSCRAM = {
        categories = {"ARMSCRAM"},
        name = "ARM Fibber - Sonar Jamming Sub",
        tooltip = "Disable the ARM Fibber",
    },
    ARMSEAP = {
        categories = {"ARMSEAP"},
        name = "ARM Albatross - Torpedo Seaplane",
        tooltip = "Disable the ARM Albatross",
    },
    ARMSEER = {
        categories = {"ARMSEER"},
        name = "ARM Seer - Mobile Radar",
        tooltip = "Disable the ARM Seer",
    },
    ARMSEHAK = {
        categories = {"ARMSEHAK"},
        name = "ARM Seahawk - Airborne Sonar",
        tooltip = "Disable the ARM Seahawk",
    },
    ARMSFIG = {
        categories = {"ARMSFIG"},
        name = "ARM Tornado - Seaplane Fighter",
        tooltip = "Disable the ARM Tornado",
    },
    ARMSH = {
        categories = {"ARMSH"},
        name = "ARM Skimmer - Scout Hovercraft",
        tooltip = "Disable the ARM Skimmer",
    },
    ARMSILO = {
        categories = {"ARMSILO"},
        name = "ARM Retaliator - Nuclear Missile Launcher",
        tooltip = "Disable the ARM Retaliator",
    },
    ARMSJAM = {
        categories = {"ARMSJAM"},
        name = "ARM Escort - Radar Jammer Ship",
        tooltip = "Disable the ARM Escort",
    },
    ARMSNIPE = {
        categories = {"ARMSNIPE"},
        name = "ARM Shooter - Sniper Kbot",
        tooltip = "Disable the ARM Shooter",
    },
    ARMSOLAR = {
        categories = {"ARMSOLAR"},
        name = "ARM Solar Collector - Produces Energy",
        tooltip = "Disable the ARM Solar Collector",
    },
    ARMSONAR = {
        categories = {"ARMSONAR"},
        name = "ARM Sonar Station - Locates Water Units",
        tooltip = "Disable the ARM Sonar Station",
    },
    ARMSPID = {
        categories = {"ARMSPID"},
        name = "ARM Spider - Spider Assault Vehicle",
        tooltip = "Disable the ARM Spider",
    },
    ARMSPY = {
        categories = {"ARMSPY"},
        name = "ARM Infiltrator - SPY Kbot",
        tooltip = "Disable the ARM Infiltrator",
    },
    ARMSTUMP = {
        categories = {"ARMSTUMP"},
        name = "ARM Stumpy - Medium Assault Tank",
        tooltip = "Disable the ARM Stumpy",
    },
    ARMSUB = {
        categories = {"ARMSUB"},
        name = "ARM Lurker - Submarine",
        tooltip = "Disable the ARM Lurker",
    },
    ARMSUBK = {
        categories = {"ARMSUBK"},
        name = "ARM Piranha - Submarine Killer",
        tooltip = "Disable the ARM Piranha",
    },
    ARMSY = {
        categories = {"ARMSY"},
        name = "ARM Shipyard - Produces Ships",
        tooltip = "Disable the ARM Shipyard",
    },
    ARMTARG = {
        categories = {"ARMTARG"},
        name = "ARM Targeting Facility - Automatic Radar Targeting",
        tooltip = "Disable the ARM Targeting Facility",
    },
    ARMTHOVR = {
        categories = {"ARMTHOVR"},
        name = "ARM Bear - Transport Hovercraft",
        tooltip = "Disable the ARM Bear",
    },
    ARMTHUND = {
        categories = {"ARMTHUND"},
        name = "ARM Thunder - Bomber",
        tooltip = "Disable the ARM Thunder",
    },
    ARMTIDE = {
        categories = {"ARMTIDE"},
        name = "ARM Tidal Generator - Produces Energy",
        tooltip = "Disable the ARM Tidal Generator",
    },
    ARMTL = {
        categories = {"ARMTL"},
        name = "ARM Torpedo Launcher - Torpedo Launcher",
        tooltip = "Disable the ARM Torpedo Launcher",
    },
    ARMUWES = {
        categories = {"ARMUWES"},
        name = "ARM Underwater Energy Storage - Increases Energy Storage",
        tooltip = "Disable the ARM Underwater Energy Storage",
    },
    ARMUWFUS = {
        categories = {"ARMUWFUS"},
        name = "CORE Underwater Fusion Plant - Produces Energy",
        tooltip = "Disable the CORE Underwater Fusion Plant",
    },
    ARMUWMEX = {
        categories = {"ARMUWMEX"},
        name = "CORE Underwater Metal Extractor - Extracts Metal",
        tooltip = "Disable the CORE Underwater Metal Extractor",
    },
    ARMUWMS = {
        categories = {"ARMUWMS"},
        name = "CORE Underwater Metal Storage - Increases Metal Storage",
        tooltip = "Disable the CORE Underwater Metal Storage",
    },
    ARMVADER = {
        categories = {"ARMVADER"},
        name = "CORE Invader - Crawling Bomb",
        tooltip = "Disable the CORE Invader",
    },
    ARMVP = {
        categories = {"ARMVP"},
        name = "CORE Vehicle Plant - Produces Vehicles",
        tooltip = "Disable the CORE Vehicle Plant",
    },
    Armvulc = {
        categories = {"Armvulc"},
        name = "CORE Vulcan - Rapid Fire Plasma Cannon",
        tooltip = "Disable the CORE Vulcan",
    },
    ARMWAR = {
        categories = {"ARMWAR"},
        name = "CORE Warrior - Medium Infantry Kbot",
        tooltip = "Disable the CORE Warrior",
    },
    ARMWIN = {
        categories = {"ARMWIN"},
        name = "CORE Wind Generator - Produces Energy",
        tooltip = "Disable the CORE Wind Generator",
    },
    ARMYORK = {
        categories = {"ARMYORK"},
        name = "CORE Phalanx - Mobile Flak Vehicle",
        tooltip = "Disable the CORE Phalanx",
    },
    ARMZEUS = {
        categories = {"ARMZEUS"},
        name = "CORE Zeus - Assault Kbot",
        tooltip = "Disable the CORE Zeus",
    },
    CORAAP = {
        categories = {"CORAAP"},
        name = "CORE Adv. Aircraft Plant - Produces Aircraft",
        tooltip = "Disable the CORE Adv. Aircraft Plant",
    },
    CORACA = {
        categories = {"CORACA"},
        name = "CORE Adv. Construction Aircraft - Tech Level 2",
        tooltip = "Disable the CORE Adv. Construction Aircraft",
    },
    CORACK = {
        categories = {"CORACK"},
        name = "CORE Adv. Construction Kbot - Tech Level 2",
        tooltip = "Disable the CORE Adv. Construction Kbot",
    },
    CORACSUB = {
        categories = {"CORACSUB"},
        name = "CORE Adv. Construction Sub - Tech Level 2",
        tooltip = "Disable the CORE Adv. Construction Sub",
    },
    CORACV = {
        categories = {"CORACV"},
        name = "CORE Adv. Construction Vehicle - Tech Level 2",
        tooltip = "Disable the CORE Adv. Construction Vehicle",
    },
    CORAH = {
        categories = {"CORAH"},
        name = "CORE Slinger - Anti-Air Hovercraft",
        tooltip = "Disable the CORE Slinger",
    },
    CORAK = {
        categories = {"CORAK"},
        name = "CORE A.K. - Infantry Kbot",
        tooltip = "Disable the CORE A.K.",
    },
    CORALAB = {
        categories = {"CORALAB"},
        name = "CORE Adv. Kbot Lab - Produces Kbots",
        tooltip = "Disable the CORE Adv. Kbot Lab",
    },
    CORAMPH = {
        categories = {"CORAMPH"},
        name = "CORE Gimp - Amphibious Kbot",
        tooltip = "Disable the CORE Gimp",
    },
    CORAP = {
        categories = {"CORAP"},
        name = "CORE Aircraft Plant - Produces Aircraft",
        tooltip = "Disable the CORE Aircraft Plant",
    },
    CORAPE = {
        categories = {"CORAPE"},
        name = "CORE Rapier - Gunship",
        tooltip = "Disable the CORE Rapier",
    },
    CORARAD = {
        categories = {"CORARAD"},
        name = "CORE Adv. Radar Tower - Long Range Radar",
        tooltip = "Disable the CORE Adv. Radar Tower",
    },
    CORARCH = {
        categories = {"CORARCH"},
        name = "CORE Shredder - Anti-Air Ship",
        tooltip = "Disable the CORE Shredder",
    },
    CORASON = {
        categories = {"CORASON"},
        name = "CORE Adv. Sonar Station - Locates Water Units",
        tooltip = "Disable the CORE Adv. Sonar Station",
    },
    CORASP = {
        categories = {"CORASP"},
        name = "CORE Air Repair Pad - Automatically repairs aircraft",
        tooltip = "Disable the CORE Air Repair Pad",
    },
    CORASY = {
        categories = {"CORASY"},
        name = "CORE Adv. Shipyard - Produces Ships",
        tooltip = "Disable the CORE Adv. Shipyard",
    },
    CORATL = {
        categories = {"CORATL"},
        name = "CORE Adv. Torpedo Launcher - Advanced Torpedo Launcher",
        tooltip = "Disable the CORE Adv. Torpedo Launcher",
    },
    CORAVP = {
        categories = {"CORAVP"},
        name = "CORE Adv. Vehicle Plant - Produces Vehicles",
        tooltip = "Disable the CORE Adv. Vehicle Plant",
    },
    CORAWAC = {
        categories = {"CORAWAC"},
        name = "CORE Vulture - Radar Plane",
        tooltip = "Disable the CORE Vulture",
    },
    CORBATS = {
        categories = {"CORBATS"},
        name = "CORE Warlord - Battleship",
        tooltip = "Disable the CORE Warlord",
    },
    Corbuzz = {
        categories = {"Corbuzz"},
        name = "CORE Buzzsaw - Rapid Fire Plasma Cannon",
        tooltip = "Disable the CORE Buzzsaw",
    },
    CORCA = {
        categories = {"CORCA"},
        name = "CORE Construction Aircraft - Tech Level 1",
        tooltip = "Disable the CORE Construction Aircraft",
    },
    CORCAN = {
        categories = {"CORCAN"},
        name = "CORE The Can - Armored Assault Kbot",
        tooltip = "Disable the CORE The Can",
    },
    CORCARRY = {
        categories = {"CORCARRY"},
        name = "CORE Hive - Light Carrier",
        tooltip = "Disable the CORE Hive",
    },
    CORCH = {
        categories = {"CORCH"},
        name = "CORE Construction Hovercraft - Tech Level 1",
        tooltip = "Disable the CORE Construction Hovercraft",
    },
    CORCK = {
        categories = {"CORCK"},
        name = "CORE Construction Kbot - Tech Level 1",
        tooltip = "Disable the CORE Construction Kbot",
    },
    Corckfus = {
        categories = {"Corckfus"},
        name = "CORE Cloakable Fusion Reactor - Produces Energy",
        tooltip = "Disable the CORE Cloakable Fusion Reactor",
    },
    CORCOM = {
        categories = {"CORCOM"},
        name = "CORE Commander - Commander",
        tooltip = "Disable the CORE Commander",
    },
    CORCRASH = {
        categories = {"CORCRASH"},
        name = "CORE Crasher - Missile Kbot",
        tooltip = "Disable the CORE Crasher",
    },
    CORCRUS = {
        categories = {"CORCRUS"},
        name = "CORE Executioner - Cruiser",
        tooltip = "Disable the CORE Executioner",
    },
    CORCS = {
        categories = {"CORCS"},
        name = "CORE Construction Ship - Tech Level 1",
        tooltip = "Disable the CORE Construction Ship",
    },
    Corcsa = {
        categories = {"Corcsa"},
        name = "CORE Construction Seaplane - Tech Level 1",
        tooltip = "Disable the CORE Construction Seaplane",
    },
    CORCV = {
        categories = {"CORCV"},
        name = "CORE Construction Vehicle - Tech Level 1",
        tooltip = "Disable the CORE Construction Vehicle",
    },
    Cordecom = {
        categories = {"Cordecom"},
        name = "CORE Commander - Decoy Commander",
        tooltip = "Disable the CORE Commander",
    },
    CORDOOM = {
        categories = {"CORDOOM"},
        name = "CORE Doomsday Machine - Energy Weapon",
        tooltip = "Disable the CORE Doomsday Machine",
    },
    CORDRAG = {
        categories = {"CORDRAG"},
        name = "CORE Dragon's Teeth - Perimeter Defense",
        tooltip = "Disable the CORE Dragon's Teeth",
    },
    CORESTOR = {
        categories = {"CORESTOR"},
        name = "CORE Energy Storage - Increases Energy Storage",
        tooltip = "Disable the CORE Energy Storage",
    },
    CORETER = {
        categories = {"CORETER"},
        name = "CORE Deleter - Mobile Radar Jammer",
        tooltip = "Disable the CORE Deleter",
    },
    CORFAST = {
        categories = {"CORFAST"},
        name = "CORE Freaker - Fast Attack Kbot",
        tooltip = "Disable the CORE Freaker",
    },
    CORFAV = {
        categories = {"CORFAV"},
        name = "CORE Weasel - Scout",
        tooltip = "Disable the CORE Weasel",
    },
    CORFDRAG = {
        categories = {"CORFDRAG"},
        name = "CORE Floating Dragon's Teeth - Floating Dragon's Teeth",
        tooltip = "Disable the CORE Floating Dragon's Teeth",
    },
    CORFHLT = {
        categories = {"CORFHLT"},
        name = "CORE Thunderbolt - Floating Heavy Laser Tower",
        tooltip = "Disable the CORE Thunderbolt",
    },
    CORFINK = {
        categories = {"CORFINK"},
        name = "CORE Fink - Air Scout",
        tooltip = "Disable the CORE Fink",
    },
    CORFLAK = {
        categories = {"CORFLAK"},
        name = "CORE Cobra - Anti-Air Flak Gun",
        tooltip = "Disable the CORE Cobra",
    },
    CORFMD = {
        categories = {"CORFMD"},
        name = "CORE Fortitude Missile Defense - Anti Missile Defense System",
        tooltip = "Disable the CORE Fortitude Missile Defense",
    },
    CORFMKR = {
        categories = {"CORFMKR"},
        name = "CORE Floating Metal Maker - Floating Metal Maker",
        tooltip = "Disable the CORE Floating Metal Maker",
    },
    CORFORT = {
        categories = {"CORFORT"},
        name = "CORE Fortification Wall - Perimeter Defense",
        tooltip = "Disable the CORE Fortification Wall",
    },
    CORFRT = {
        categories = {"CORFRT"},
        name = "CORE Stinger - Missile Tower - Naval Series",
        tooltip = "Disable the CORE Stinger",
    },
    CORFUS = {
        categories = {"CORFUS"},
        name = "CORE Fusion Power Plant - Produces Energy",
        tooltip = "Disable the CORE Fusion Power Plant",
    },
    CORGANT = {
        categories = {"CORGANT"},
        name = "CORE Krogoth Gantry - Builds Krogoth",
        tooltip = "Disable the CORE Krogoth Gantry",
    },
    CORGATOR = {
        categories = {"CORGATOR"},
        name = "CORE Instigator - Assault Tank",
        tooltip = "Disable the CORE Instigator",
    },
    CORGEO = {
        categories = {"CORGEO"},
        name = "CORE Geothermal Powerplant - Produces Energy",
        tooltip = "Disable the CORE Geothermal Powerplant",
    },
    CORGOL = {
        categories = {"CORGOL"},
        name = "CORE Goliath - Very Heavy Assault Tank",
        tooltip = "Disable the CORE Goliath",
    },
    CORHLT = {
        categories = {"CORHLT"},
        name = "CORE Gaat Gun - Heavy Laser Tower",
        tooltip = "Disable the CORE Gaat Gun",
    },
    CORHP = {
        categories = {"CORHP"},
        name = "CORE Hovercraft Platform - Builds Hovercraft",
        tooltip = "Disable the CORE Hovercraft Platform",
    },
    CORHRK = {
        categories = {"CORHRK"},
        name = "CORE Dominator - Heavy Rocket Kbot",
        tooltip = "Disable the CORE Dominator",
    },
    CORHUNT = {
        categories = {"CORHUNT"},
        name = "CORE Hunter - Airborne Sonar",
        tooltip = "Disable the CORE Hunter",
    },
    CORHURC = {
        categories = {"CORHURC"},
        name = "CORE Hurricane - Strategic Bomber",
        tooltip = "Disable the CORE Hurricane",
    },
    CORINT = {
        categories = {"CORINT"},
        name = "CORE Intimidator - Long Range Plasma Cannon",
        tooltip = "Disable the CORE Intimidator",
    },
    CORKROG = {
        categories = {"CORKROG"},
        name = "CORE Krogoth - Experimental Kbot",
        tooltip = "Disable the CORE Krogoth",
    },
    CORLAB = {
        categories = {"CORLAB"},
        name = "CORE Kbot Lab - Produces Kbots",
        tooltip = "Disable the CORE Kbot Lab",
    },
    CORLEVLR = {
        categories = {"CORLEVLR"},
        name = "CORE Leveler - Riot Tank",
        tooltip = "Disable the CORE Leveler",
    },
    CORLLT = {
        categories = {"CORLLT"},
        name = "CORE Light Laser Tower - Light Laser Tower",
        tooltip = "Disable the CORE Light Laser Tower",
    },
    CORMAKR = {
        categories = {"CORMAKR"},
        name = "CORE Metal Maker - Metal Maker",
        tooltip = "Disable the CORE Metal Maker",
    },
    CORMART = {
        categories = {"CORMART"},
        name = "CORE Pillager - Mobile Artillery",
        tooltip = "Disable the CORE Pillager",
    },
    CORMEX = {
        categories = {"CORMEX"},
        name = "CORE Metal Extractor - Extracts Metal",
        tooltip = "Disable the CORE Metal Extractor",
    },
    CORMH = {
        categories = {"CORMH"},
        name = "CORE Nixer - Hovercraft Rocket Launcher",
        tooltip = "Disable the CORE Nixer",
    },
    CORMINE1 = {
        categories = {"CORMINE1"},
        name = "CORE M-104 Mine - Low Damage, Med. Range Mine",
        tooltip = "Disable the CORE M-104 Mine",
    },
    CORMINE2 = {
        categories = {"CORMINE2"},
        name = "CORE M-209 Mine - Low Damage, Large Range Mine",
        tooltip = "Disable the CORE M-209 Mine",
    },
    CORMINE3 = {
        categories = {"CORMINE3"},
        name = "CORE M-303 Mine - Med. Damage, Med. Range Mine",
        tooltip = "Disable the CORE M-303 Mine",
    },
    CORMINE4 = {
        categories = {"CORMINE4"},
        name = "CORE M-420 Mine - High Damage, Med. Range Mine",
        tooltip = "Disable the CORE M-420 Mine",
    },
    CORMINE5 = {
        categories = {"CORMINE5"},
        name = "CORE M-515 Mine - High Damage, Large Range Mine",
        tooltip = "Disable the CORE M-515 Mine",
    },
    CORMINE6 = {
        categories = {"CORMINE6"},
        name = "CORE M-610 Mine - Nuclear Mine",
        tooltip = "Disable the CORE M-610 Mine",
    },
    CORMIST = {
        categories = {"CORMIST"},
        name = "CORE Slasher - Missile Launcher",
        tooltip = "Disable the CORE Slasher",
    },
    CORMLV = {
        categories = {"CORMLV"},
        name = "CORE Spoiler - Mine Layer Vehicle",
        tooltip = "Disable the CORE Spoiler",
    },
    CORMMKR = {
        categories = {"CORMMKR"},
        name = "CORE Moho Metal Maker - Produces Metal",
        tooltip = "Disable the CORE Moho Metal Maker",
    },
    CORMOHO = {
        categories = {"CORMOHO"},
        name = "CORE Moho Mine - Advanced Metal Extractor",
        tooltip = "Disable the CORE Moho Mine",
    },
    CORMORT = {
        categories = {"CORMORT"},
        name = "CORE Morty - Mobile Mortar Kbot",
        tooltip = "Disable the CORE Morty",
    },
    CORMSHIP = {
        categories = {"CORMSHIP"},
        name = "CORE Hydra - Missile Ship",
        tooltip = "Disable the CORE Hydra",
    },
    CORMSTOR = {
        categories = {"CORMSTOR"},
        name = "CORE Metal Storage - Increases Metal Storage",
        tooltip = "Disable the CORE Metal Storage",
    },
    CORPLAT = {
        categories = {"CORPLAT"},
        name = "CORE Seaplane Platform - Builds Seaplanes",
        tooltip = "Disable the CORE Seaplane Platform",
    },
    CORPT = {
        categories = {"CORPT"},
        name = "CORE Searcher - Scout Ship",
        tooltip = "Disable the CORE Searcher",
    },
    CORPUN = {
        categories = {"CORPUN"},
        name = "CORE Punisher - Plasma Battery",
        tooltip = "Disable the CORE Punisher",
    },
    CORPYRO = {
        categories = {"CORPYRO"},
        name = "CORE Pyro - Assault Kbot",
        tooltip = "Disable the CORE Pyro",
    },
    CORRAD = {
        categories = {"CORRAD"},
        name = "CORE Radar Tower - Radar Tower",
        tooltip = "Disable the CORE Radar Tower",
    },
    CORRAID = {
        categories = {"CORRAID"},
        name = "CORE Raider - Medium Assault Tank",
        tooltip = "Disable the CORE Raider",
    },
    CORREAP = {
        categories = {"CORREAP"},
        name = "CORE Reaper - Heavy Assault Tank",
        tooltip = "Disable the CORE Reaper",
    },
    CORRL = {
        categories = {"CORRL"},
        name = "CORE Pulverizer - Missile Tower",
        tooltip = "Disable the CORE Pulverizer",
    },
    CORROACH = {
        categories = {"CORROACH"},
        name = "CORE Roach - Crawling Bomb",
        tooltip = "Disable the CORE Roach",
    },
    CORROY = {
        categories = {"CORROY"},
        name = "CORE Enforcer - Destroyer",
        tooltip = "Disable the CORE Enforcer",
    },
    CORSEAL = {
        categories = {"CORSEAL"},
        name = "CORE Crock - Amphibious Tank",
        tooltip = "Disable the CORE Crock",
    },
    CORSEAP = {
        categories = {"CORSEAP"},
        name = "CORE Typhoon - Torpedo Seaplane",
        tooltip = "Disable the CORE Typhoon",
    },
    CORSENT = {
        categories = {"CORSENT"},
        name = "CORE Copperhead - Mobile Flak Vehicle",
        tooltip = "Disable the CORE Copperhead",
    },
    CORSFIG = {
        categories = {"CORSFIG"},
        name = "CORE Voodoo - Seaplane Fighter",
        tooltip = "Disable the CORE Voodoo",
    },
    CORSH = {
        categories = {"CORSH"},
        name = "CORE Scrubber - Scout Hovercraft",
        tooltip = "Disable the CORE Scrubber",
    },
    CORSHAD = {
        categories = {"CORSHAD"},
        name = "CORE Shadow - Bomber",
        tooltip = "Disable the CORE Shadow",
    },
    CORSHARK = {
        categories = {"CORSHARK"},
        name = "CORE Shark - Submarine Killer",
        tooltip = "Disable the CORE Shark",
    },
    CORSILO = {
        categories = {"CORSILO"},
        name = "CORE Silencer - Nuclear Missile Launcher",
        tooltip = "Disable the CORE Silencer",
    },
    CORSJAM = {
        categories = {"CORSJAM"},
        name = "CORE Phantom - Radar Jammer Ship",
        tooltip = "Disable the CORE Phantom",
    },
    CORSNAP = {
        categories = {"CORSNAP"},
        name = "CORE Snapper - Hovertank",
        tooltip = "Disable the CORE Snapper",
    },
    CORSOLAR = {
        categories = {"CORSOLAR"},
        name = "CORE Solar Collector - Produces Energy",
        tooltip = "Disable the CORE Solar Collector",
    },
    CORSONAR = {
        categories = {"CORSONAR"},
        name = "CORE Sonar Station - Sonar Station",
        tooltip = "Disable the CORE Sonar Station",
    },
    CORSPEC = {
        categories = {"CORSPEC"},
        name = "CORE Spectre - Radar Jammer",
        tooltip = "Disable the CORE Spectre",
    },
    CORSPY = {
        categories = {"CORSPY"},
        name = "CORE Parasite - SPY Kbot",
        tooltip = "Disable the CORE Parasite",
    },
    CORSSUB = {
        categories = {"CORSSUB"},
        name = "CORE Leviathan - Battle Sub",
        tooltip = "Disable the CORE Leviathan",
    },
    CORSTORM = {
        categories = {"CORSTORM"},
        name = "CORE Storm - Rocket Kbot",
        tooltip = "Disable the CORE Storm",
    },
    CORSUB = {
        categories = {"CORSUB"},
        name = "CORE Snake - Submarine",
        tooltip = "Disable the CORE Snake",
    },
    CORSUMO = {
        categories = {"CORSUMO"},
        name = "CORE Sumo - Adv. Armored Assault Kbot",
        tooltip = "Disable the CORE Sumo",
    },
    CORSY = {
        categories = {"CORSY"},
        name = "CORE Shipyard - Produces Ships",
        tooltip = "Disable the CORE Shipyard",
    },
    CORTARG = {
        categories = {"CORTARG"},
        name = "CORE Targeting Facility - Automatic Radar Targeting",
        tooltip = "Disable the CORE Targeting Facility",
    },
    CORTHOVR = {
        categories = {"CORTHOVR"},
        name = "CORE Turtle - Transport Hovercraft",
        tooltip = "Disable the CORE Turtle",
    },
    CORTHUD = {
        categories = {"CORTHUD"},
        name = "CORE Thud - Artillery Kbot",
        tooltip = "Disable the CORE Thud",
    },
    CORTIDE = {
        categories = {"CORTIDE"},
        name = "CORE Tidal Generator - Produces Energy",
        tooltip = "Disable the CORE Tidal Generator",
    },
    CORTITAN = {
        categories = {"CORTITAN"},
        name = "CORE Titan - Torpedo Bomber",
        tooltip = "Disable the CORE Titan",
    },
    CORTL = {
        categories = {"CORTL"},
        name = "CORE Torpedo Launcher - Torpedo Launcher",
        tooltip = "Disable the CORE Torpedo Launcher",
    },
    CORTOAST = {
        categories = {"CORTOAST"},
        name = "CORE Toaster - Pop-up Heavy Cannon",
        tooltip = "Disable the CORE Toaster",
    },
    CORTRON = {
        categories = {"CORTRON"},
        name = "CORE Neutron - Neutron Missile Launcher",
        tooltip = "Disable the CORE Neutron",
    },
    CORUWES = {
        categories = {"CORUWES"},
        name = "CORE Underwater Energy Storage - Ground Transport",
        tooltip = "Disable the CORE Underwater Energy Storage",
    },
    CORUWFUS = {
        categories = {"CORUWFUS"},
        name = "CORE Underwater Fusion Plant - Increases Energy Storage",
        tooltip = "Disable the CORE Underwater Fusion Plant",
    },
    CORUWMEX = {
        categories = {"CORUWMEX"},
        name = "CORE Underwater Metal Extractor - Produces Energy",
        tooltip = "Disable the CORE Underwater Metal Extractor",
    },
    CORUWMS = {
        categories = {"CORUWMS"},
        name = "CORE Underwater Metal Storage - Extracts Metal",
        tooltip = "Disable the CORE Underwater Metal Storage",
    },
    CORVALK = {
        categories = {"CORVALK"},
        name = "CORE Valkyrie - Increases Metal Storage",
        tooltip = "Disable the CORE Valkyrie",
    },
    CORVAMP = {
        categories = {"CORVAMP"},
        name = "CORE Vamp - Air Transport",
        tooltip = "Disable the CORE Vamp",
    },
    CORVENG = {
        categories = {"CORVENG"},
        name = "CORE Avenger - Stealth Fighter",
        tooltip = "Disable the CORE Avenger",
    },
    CORVIPE = {
        categories = {"CORVIPE"},
        name = "CORE Viper - Fighter",
        tooltip = "Disable the CORE Viper",
    },
    CORVOYR = {
        categories = {"CORVOYR"},
        name = "CORE Voyeur - Pop-Up Heavy Laser",
        tooltip = "Disable the CORE Voyeur",
    },
    CORVP = {
        categories = {"CORVP"},
        name = "CORE Vehicle Plant - Mobile Radar Kbot",
        tooltip = "Disable the CORE Vehicle Plant",
    },
    CORVRAD = {
        categories = {"CORVRAD"},
        name = "CORE Informer - Produces Vehicles",
        tooltip = "Disable the CORE Informer",
    },
    CORVROC = {
        categories = {"CORVROC"},
        name = "CORE Diplomat - Mobile Radar",
        tooltip = "Disable the CORE Diplomat",
    },
    CORWIN = {
        categories = {"CORWIN"},
        name = "CORE Wind Generator - Mobile Rocket Launcher",
        tooltip = "Disable the CORE Wind Generator",
    },
    T1 = {
        categories = {"TECH1"},
        name = "<LOC restricted_units_data_0000>FA: No Tech 1",
        tooltip = "restricted_uints_T1",
    },
    T2 = {
        categories = {"TECH2"},
        name = "<LOC restricted_units_data_0001>FA: No Tech 2",
        tooltip = "restricted_uints_T2",
    },
    T3 = {
        categories = {"TECH3"},
        name = "<LOC restricted_units_data_0002>FA: No Tech 3",
        tooltip = "restricted_uints_T3",
    },
    EXPERIMENTAL = {
        categories = {"EXPERIMENTAL"},
        name = "<LOC restricted_units_data_0003>FA: No Experimental",
        tooltip = "restricted_uints_experimental",
    },
    NAVAL = {
        categories = {"NAVAL"},
        name = "<LOC restricted_units_data_0004>FA: No Naval",
        tooltip = "restricted_uints_naval",
    },
    LAND = {
        categories = {"LAND"},
        name = "<LOC restricted_units_data_0005>FA: No Land",
        tooltip = "restricted_uints_land",
    },
    AIR = {
        categories = {"AIR"},
        name = "<LOC restricted_units_data_0006>FA: No Air",
        tooltip = "restricted_uints_air",
    },
    UEF = {
        categories = {"UEF"},
        name = "<LOC restricted_units_data_0007>FA: No UEF",
        tooltip = "restricted_uints_uef",
    },
    CYBRAN = {
        categories = {"CYBRAN"},
        name = "<LOC restricted_units_data_0008>FA: No Cybran",
        tooltip = "restricted_uints_cybran",
    },
    AEON = {
        categories = {"AEON"},
        name = "<LOC restricted_units_data_0009>FA: No Aeon",
        tooltip = "restricted_uints_aeon",
    },
    SERAPHIM = {
        categories = {"SERAPHIM"},
        name = "<LOC restricted_units_data_0010>FA: No Seraphim",
        tooltip = "restricted_uints_seraphim",
    },
    NUKE = {
        categories = {"uab2305", "ueb2305", "urb2305", "xsb2305", "xsb2401", "xss0302", "xsb4302", "ueb4302", "urb4302", "uab4302", "uas0304", "urs0304", "ues0304" },
        name = "<LOC restricted_units_data_0011>FA: No Nukes",
        tooltip = "restricted_uints_nukes",
    },
    GAMEENDERS = {
        categories = {"uab2302", "urb2302", "ueb2302", "xsb2302", "xab1401", "xab2307", "url0401", "xeb2402", "ueb2401", "xsb2401"},
        name = "<LOC restricted_units_data_0012>FA: No Game Enders",
        tooltip = "restricted_uints_gameenders",
    },
    BUBBLES = {
        categories = {"uel0307", "ual0307", "xsl0307", "deb4303", "xes0205", "ueb4202", "urb4202", "uab4202", "xsb4202", "ueb4301", "uab4301", "xsb4301", },
        name = "<LOC restricted_units_data_0013>FA: No Bubbles",
        tooltip = "restricted_uints_bubbles",
    },
    INTEL = {
        categories = {"OMNI", "uab3101", "uab3201", "ueb3101", "ueb3201", "urb3101", "urb3201", "xsb3101", "xsb3201", "uab3102", "uab3202", "ueb3102", "ueb3202", "urb3102", "urb3202", "xsb3102", "xsb3202", "xab3301", "xrb3301", "ues0305", "uas0305", "urs0305", },
        name = "<LOC restricted_units_data_0014>FA: No Intel Structures",
        tooltip = "restricted_uints_intel",
    },
    SUPCOM = {
        categories = {"SUBCOMMANDER", },
        name = "<LOC restricted_units_data_0015>FA: No Support Commanders",
        tooltip = "restricted_uints_supcom",
    },
    PRODSC1 = {
        categories = {"PRODUCTSC1", },
        name = "<LOC restricted_units_data_0016>FA: No Supreme Commander",
        tooltip = "restricted_units_supremecommander",
    },
    PRODFA = {
        categories = {"PRODUCTFA", },
        name = "<LOC restricted_units_data_0017>FA: No Forged Alliance",
        tooltip = "restricted_units_forgedalliance",
    },
    PRODDL = {
        categories = {"PRODUCTDL", },
        name = "<LOC restricted_units_data_0018>FA: No Downloaded",
        tooltip = "restricted_units_downloaded",
    },
    FABS = {
        categories = {"ueb1104", "ueb1303", "urb1104", "urb1303", "uab1104", "uab1303", "xsb1104", "xsb1303", },
        name = "<LOC restricted_units_data_0019>FA: No Mass Fabrication",
        tooltip = "restricted_units_massfab",
    },
}

#TODO:
--[[
KBOT Level 1
KBOT Level 2
Vehicle Level 1
Vehicle Level 2
Aircraft Level 1
Aircraft Level 2
Hovercraft
Seaplanes
Krogoth
Structures Level 1
Structures Level 2
Structures Level 3
Nukes
Long Range Cannons
Metal Makers
--]]

sortOrder = {
"ARMAAP",
"ARMAAS",
"ARMACA",
"ARMACK",
"ARMACSUB",
"ARMACV",
"ARMAH",
"ARMALAB",
"ARMAMB",
"ARMAMD",
"ARMAMPH",
"ARMANAC",
"ARMANNI",
"ARMAP",
"ARMARAD",
"ARMASER",
"ARMASON",
"ARMASP",
"ARMASY",
"ARMATL",
"ARMATLAS",
"ARMAVP",
"ARMAWAC",
"ARMBATS",
"ARMBRAWL",
"ARMBRTHA",
"ARMBULL",
"ARMCA",
"ARMCARRY",
"ARMCH",
"ARMCK",
"ARMCKFUS",
"ARMCOM",
"ARMCROC",
"ARMCRUS",
"ARMCS",
"Armcsa",
"ARMCV",
"ARMDECOM",
"ARMDRAG",
"ARMEMP",
"ARMESTOR",
"ARMFAST",
"ARMFAV",
"ARMFDRAG",
"ARMFHLT",
"ARMFIDO",
"ARMFIG",
"ARMFLAK",
"ARMFLASH",
"ARMFMKR",
"ARMFORT",
"ARMFRT",
"ARMFUS",
"ARMGEO",
"ARMGUARD",
"ARMHAM",
"ARMHAWK",
"ARMHLT",
"ARMHP",
"ARMJAM",
"ARMJETH",
"ARMLAB",
"ARMLANCE",
"ARMLATNK",
"ARMLLT",
"ARMMAKR",
"ARMMANNI",
"ARMMARK",
"ARMMART",
"ARMMAV",
"ARMMERL",
"ARMMEX",
"ARMMH",
"ARMMINE1",
"ARMMINE2",
"ARMMINE3",
"ARMMINE4",
"ARMMINE5",
"ARMMINE6",
"ARMMLV",
"ARMMMKR",
"ARMMOHO",
"ARMMSHIP",
"ARMMSTOR",
"ARMPEEP",
"ARMPLAT",
"ARMPNIX",
"ARMPT",
"ARMPW",
"ARMRAD",
"ARMRL",
"ARMROCK",
"ARMROY",
"ARMSAM",
"ARMSCRAM",
"ARMSEAP",
"ARMSEER",
"ARMSEHAK",
"ARMSFIG",
"ARMSH",
"ARMSILO",
"ARMSJAM",
"ARMSNIPE",
"ARMSOLAR",
"ARMSONAR",
"ARMSPID",
"ARMSPY",
"ARMSTUMP",
"ARMSUB",
"ARMSUBK",
"ARMSY",
"ARMTARG",
"ARMTHOVR",
"ARMTHUND",
"ARMTIDE",
"ARMTL",
"ARMUWES",
"ARMUWFUS",
"ARMUWMEX",
"ARMUWMS",
"ARMVADER",
"ARMVP",
"Armvulc",
"ARMWAR",
"ARMWIN",
"ARMYORK",
"ARMZEUS",
"CORAAP",
"CORACA",
"CORACK",
"CORACSUB",
"CORACV",
"CORAH",
"CORAK",
"CORALAB",
"CORAMPH",
"CORAP",
"CORAPE",
"CORARAD",
"CORARCH",
"CORASON",
"CORASP",
"CORASY",
"CORATL",
"CORAVP",
"CORAWAC",
"CORBATS",
"Corbuzz",
"CORCA",
"CORCAN",
"CORCARRY",
"CORCH",
"CORCK",
"Corckfus",
"CORCOM",
"CORCRASH",
"CORCRUS",
"CORCS",
"Corcsa",
"CORCV",
"Cordecom",
"CORDOOM",
"CORDRAG",
"CORESTOR",
"CORETER",
"CORFAST",
"CORFAV",
"CORFDRAG",
"CORFHLT",
"CORFINK",
"CORFLAK",
"CORFMD",
"CORFMKR",
"CORFORT",
"CORFRT",
"CORFUS",
"CORGANT",
"CORGATOR",
"CORGEO",
"CORGOL",
"CORHLT",
"CORHP",
"CORHRK",
"CORHUNT",
"CORHURC",
"CORINT",
"CORKROG",
"CORLAB",
"CORLEVLR",
"CORLLT",
"CORMAKR",
"CORMART",
"CORMEX",
"CORMH",
"CORMINE1",
"CORMINE2",
"CORMINE3",
"CORMINE4",
"CORMINE5",
"CORMINE6",
"CORMIST",
"CORMLV",
"CORMMKR",
"CORMOHO",
"CORMORT",
"CORMSHIP",
"CORMSTOR",
"CORPLAT",
"CORPT",
"CORPUN",
"CORPYRO",
"CORRAD",
"CORRAID",
"CORREAP",
"CORRL",
"CORROACH",
"CORROY",
"CORSEAL",
"CORSEAP",
"CORSENT",
"CORSFIG",
"CORSH",
"CORSHAD",
"CORSHARK",
"CORSILO",
"CORSJAM",
"CORSNAP",
"CORSOLAR",
"CORSONAR",
"CORSPEC",
"CORSPY",
"CORSSUB",
"CORSTORM",
"CORSUB",
"CORSUMO",
"CORSY",
"CORTARG",
"CORTHOVR",
"CORTHUD",
"CORTIDE",
"CORTITAN",
"CORTL",
"CORTOAST",
"CORTRON",
"CORUWES",
"CORUWFUS",
"CORUWMEX",
"CORUWMS",
"CORVALK",
"CORVAMP",
"CORVENG",
"CORVIPE",
"CORVOYR",
"CORVP",
"CORVRAD",
"CORVROC",
"CORWIN",
    "GAMEENDERS",
    "NUKE",
    "PRODSC1",
    "PRODFA",
    "PRODDL",
    "UEF",
    "CYBRAN",
    "AEON",
    "SERAPHIM",
    "T1",
    "T2",
    "T3",
    "EXPERIMENTAL",
    "NAVAL",
    "LAND",
    "AIR",
    "BUBBLES",
    "INTEL",
    "SUPCOM",
    "FABS",
}